[package]
name = "ciftl-rs"
version = "0.1.0"
edition = "2021"
authors = ["sandinpool <dingyz0307@outlook.com>"]
description = "ciftl-rs is a library, which contains some cipher components."
keywords = ["crypter", "hash", "cipher"]
license = "GPL-3.0"

[lib]
name = "ciftl"
version = "0.1.0"

[[bin]]
name = "ciftl-crypter"
path = "bin/ciftl-crypter.rs"
version = "0.1.0"
required-features = ["tools"]

[dependencies]
rand = "0.8.5"
# 枚举相关
num-traits = "0.2.14"
num-derive = "0.3.3"
# 编码相关
base64 = "0.21.0"
hex = "0.4.3"
# 密码组件相关
ring = "0.17.8"
chacha20 = "0.9.1"
# 哈希相关
crc32fast = "1.4.2"
crc32c = "0.6.8"

[dependencies.prettytable]
version = "0.10.0"
optional = true

[dependencies.clap]
version = "4.5.13"
default-features = false
features = ["derive", "std", "default"]
optional = true

[features]
tools = ["clap", "prettytable"]